NumPy

1.Create a 1D array from a list.


In [ ]:
import numpy as np

list_data = [1, 2, 3, 4, 5]
array_1d = np.array(list_data)
array_1d

array([1, 2, 3, 4, 5])

2. Create a 3x3 array of zeros.


In [ ]:
import numpy as np
zeros_array = np.zeros((3, 3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3. Create a 2x2 array of ones.

In [ ]:
import numpy as np
ones_array = np.ones((2, 2))
ones_array

array([[1., 1.],
       [1., 1.]])

4. Generate array from 0 to 10 (exclusive).

In [ ]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

5. Create 5 evenly spaced numbers between 0 and 1.


In [ ]:
import numpy as np
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

6. Create a 4x4 identity matrix.

In [ ]:
import numpy as np
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

7. Reshape 1D array to 2D.

In [ ]:
array_1d = np.array([1,2,3,4,5])
array_1d

array_2d = array_1d.reshape(5,1)
array_2d

array([[1],
       [2],
       [3],
       [4],
       [5]])

8. Get the shape and dtype of an array.

In [ ]:
print("Shape of array_1d:", array_1d.shape)
print("Dtype of array_1d:", array_1d.dtype)
print("Shape of array_2d:", array_2d.shape)
print("Dtype of array_2d:", array_2d.dtype)

Shape of array_1d: (5,)
Dtype of array_1d: int64
Shape of array_2d: (5, 1)
Dtype of array_2d: int64


9. Reverse a NumPy array.

In [ ]:
reversed_array = array_1d[::-1]
reversed_array

array([5, 4, 3, 2, 1])

10. Extract even numbers from an array.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

even_numbers = arr[arr % 2 == 0]
even_numbers

array([ 2,  4,  6,  8, 10])

11. Find the max in each row.

In [ ]:
import numpy as np
matrix = np.array([[1, 3, 2], [4, 5, 6], [7, 8, 9]])
print(matrix)
max_in_rows = np.max(matrix, axis=1)
max_in_rows

[[1 3 2]
 [4 5 6]
 [7 8 9]]


array([3, 6, 9])

12. Compute the mean, std, and median of an array.


In [ ]:
import numpy as np
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
print("Median:", np.median(arr))

Mean: 5.5
Standard Deviation: 2.8722813232690143
Median: 5.5


13. Stack two arrays vertically.

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

stacked_array = np.vstack((arr1, arr2))
stacked_array

array([[1, 2, 3],
       [4, 5, 6]])

14. Stack two arrays horizontally.

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

stacked_array_horizontal = np.hstack((arr1, arr2))
stacked_array_horizontal

array([1, 2, 3, 4, 5, 6])

15. Stack two arrays horizontally.


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

stacked_array_horizontal = np.hstack((arr1, arr2))
stacked_array_horizontal

array([1, 2, 3, 4, 5, 6])

16. Find the unique values and their counts.


In [ ]:
import numpy as np

arr3 = np.array([1,2,2,4,3,6,7,5,5,6,7,8,9,7,10])
unique_values, counts = np.unique(arr3, return_counts=True)

print("Unique values:", unique_values)
print("Counts:", counts)

Unique values: [ 1  2  3  4  5  6  7  8  9 10]
Counts: [1 2 1 1 2 2 3 1 1 1]


17. Replace NaN with column means.


In [ ]:
import numpy as np
arr_with_nan = np.array([[1, 2, np.nan],
                         [4, np.nan, 6],
                         [7, 8, 9]])
print (arr_with_nan)

col_means = np.nanmean(arr_with_nan, axis=0)

nan_mask = np.isnan(arr_with_nan)

arr_with_nan[nan_mask] = np.tile(col_means, (arr_with_nan.shape[0], 1))[nan_mask]

arr_with_nan

[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


array([[1. , 2. , 7.5],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])

18. Get index of min and max values.


In [ ]:
import numpy as np
print("Index of minimum value:", np.argmin(arr))
print("Index of maximum value:", np.argmax(arr))

Index of minimum value: 0
Index of maximum value: 9


19. Create a 3D array of random integers.



In [ ]:
import numpy as np
random_3d_array = np.random.randint(0, 10, size=(2, 3, 4))
random_3d_array

array([[[9, 8, 2, 0],
        [6, 0, 5, 2],
        [8, 0, 0, 0]],

       [[1, 7, 5, 3],
        [5, 5, 1, 0],
        [0, 9, 6, 2]]])

20. Use np.where() to replace values


In [ ]:
import numpy as np

arr_where = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr_where)

replaced_arr = np.where(arr_where > 5, 0, arr_where)
replaced_arr

[ 1  2  3  4  5  6  7  8  9 10]


array([1, 2, 3, 4, 5, 0, 0, 0, 0, 0])

Pandas

1. Create a Series using a Python list.


In [ ]:
import pandas as pd

list_data = [10, 20, 30, 40, 50,60]
series_from_list = pd.Series(list_data)
series_from_list

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

2. Create a Series with custom string indices.




In [ ]:
import pandas as pd
data = [10, 20, 30, 40, 50]
index = ['a', 'b', 'c', 'd', 'e']
series_with_index = pd.Series(data, index=index)
series_with_index

a    10
b    20
c    30
d    40
e    50
dtype: int64

3. Create a Series from a dictionary.


In [ ]:
import pandas as pd
data_dict = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
series_from_dict = pd.Series(data_dict)
series_from_dict

a    10
b    20
c    30
d    40
e    50
dtype: int64

4. Access first 3 elements of a Series.


In [ ]:
series_from_list.head(3)

0    10
1    20
2    30
dtype: int64

5. Filter Series elements greater than 50.



In [ ]:
series_from_list[series_from_list > 50]

5    60
dtype: int64

6. Add two Series with different indices.



In [ ]:
import pandas as pd
series1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
series2 = pd.Series([4, 5, 6], index=['b', 'c', 'd'])
series_sum = series1 + series2
series_sum

a    NaN
b    6.0
c    8.0
d    NaN
dtype: float64


7. Multiply a Series by a scalar.


In [ ]:
series_multiplied = series_from_list * 2
series_multiplied

0     20
1     40
2     60
3     80
4    100
5    120
dtype: int64

8. Use .multiply() method to multiply with scalar.


In [ ]:
series_multiplied_method = series_from_list.multiply(2)
series_multiplied_method

0     20
1     40
2     60
3     80
4    100
5    120
dtype: int64

10. Sort Series by values descending.


In [ ]:
series_from_dict.sort_values(ascending=False)

e    50
d    40
c    30
b    20
a    10
dtype: int64

11. Sort Series by index.


In [ ]:
series_from_dict.sort_index()

a    10
b    20
c    30
d    40
e    50
dtype: int64

12. Check for null values.



In [ ]:
series_sum.isnull()

a     True
b    False
c    False
d     True
dtype: bool

14. Concatenate two Series using concat().


In [ ]:
import pandas as pd
series3 = pd.Series([7, 8, 9], index=['e', 'f', 'g'])
concatenated_series = pd.concat([series_from_dict, series3])
concatenated_series

a    10
b    20
c    30
d    40
e    50
e     7
f     8
g     9
dtype: int64

15. Concatenate two Series using append().


In [ ]:
import pandas as pd
series1 = pd.Series([1, 2, 3])
series2 = pd.Series([4, 5, 6])
appended_series = series1.append(series2)
appended_series

AttributeError: 'Series' object has no attribute 'append'

16. Retrieve first 5 elements using .head()



In [ ]:
series_from_list.head(5)

0    10
1    20
2    30
3    40
4    50
dtype: int64

17. Retrieve last 5 elements using .tail()


In [ ]:
series_from_list.tail(5)

1    20
2    30
3    40
4    50
5    60
dtype: int64

18. Convert Series to DataFrame.


In [ ]:
df_from_series = series_from_list.to_frame(name='Value')
df_from_series

Value
0     10
1     20
2     30
3     40
4     50
5     60

19. Replace NaN with 0.


In [ ]:
series_sum_filled = series_sum.fillna(0)
series_sum_filled

a    0.0
b    6.0
c    8.0
d    0.0
dtype: float64

20. Drop missing values.


In [ ]:
series_sum_dropped = series_sum.dropna()
series_sum_dropped

b    6.0
c    8.0
dtype: float64

21. Check Series data type.



In [ ]:
series_from_list.dtype

dtype('int64')